[forbes-24] Added Picture Component
aberikashvili/forbes-react-native-nx pull request #21
Opened 2023-07-03 09:14 UTC by developercommon

2023-07-06 15:51 UTC, aberikashvili commented on libs/core/src/lib/picture-component/PictureComponent.tsx
ფაილს დაარქვი `Picture.tsx`

2023-07-06 15:58 UTC, aberikashvili commented on libs/core/src/lib/picture-component/PictureComponent.tsx
> +        borderRadius={circle ? 50 : 0}
`borderRadius: 50` ყველა ზომაზე კარგად არ გამოჩნდება.

ნებისმიერ ზომაზე რომ კარგად დაჯდეს, რადიუსი უნდა მისცე `width / 2`

<img width="439" alt="image" src="https://github.com/aberikashvili/forbes-react-native-nx/assets/3863691/95e566c8-0377-449a-b3b8-373d1e18197f">

2023-07-06 16:07 UTC, aberikashvili commented on libs/core/src/lib/picture-component/PictureComponent.tsx
> +  image: {},
ცარიელი სტილების დატოვება არ გვჭირდება

2023-07-06 21:18 UTC, aberikashvili commented on libs/core/src/lib/picture-component/Picture.tsx
> +    borderColor: '#E8E8E8',
ფერები `Palette`-დან

2023-07-06 21:19 UTC, aberikashvili commented on libs/core/src/lib/picture-component/Picture.tsx
> +        style={[styles.image, { width, height }]}
`styles.image` მხოლოდ მაშინ უნდა ჰქონდეს, როცა circle = true

2023-07-06 21:20 UTC, aberikashvili commented on libs/core/src/lib/picture-component/Picture.tsx
> +export function Picture({
const -ით დაწერე

2023-07-06 21:21 UTC, aberikashvili requested changes
+ კომენტარები

2023-07-10 17:33 UTC, aberikashvili approved these changes
rebase უნდა და დაიმერჯება

2023-07-10 17:34 UTC, aberikashvili commented on libs/core/src/lib/picture-component/Picture.tsx
`lib/picture-component` შეცვალე `lib/picture`-ით

2023-07-10 17:42 UTC, developercommon commented on libs/core/src/lib/picture-component/Picture.tsx
picture-ს  რომ ვარქმევ აღიქვამს როგორც folder-ს სურათებისთვის და არა ჩვეულებრივ folder-ს

2023-07-10 18:01 UTC, aberikashvili commented on libs/core/src/lib/picture-component/Picture.tsx
რა აღიქვამს, ვინ აღიქვამს?

2023-07-10 18:47 UTC, aberikashvili commented on libs/core/src/lib/input/Input.tsx
ეს აქ რატომ არის? წაშალე

2023-07-12 08:31 UTC, merged