[forbes-15] added price component
aberikashvili/forbes-react-native-nx pull request #6
Opened 2023-06-28 12:43 UTC by developercommon

2023-07-01 22:28 UTC, aberikashvili commented on libs/core/src/lib/price/Price.tsx
> +      <Text style={styles.secondaryText}>00</Text>
შეგიძლია უფრო მარტივად გააკეთო, `props.num.toFixed(2)`.
```
num = 1, props.num.toFixed(2) -> '1.00'
num = 500, props.num.toFixed(2) -> '500.00'
```

2023-07-01 22:31 UTC, aberikashvili commented on tsconfig.json
ეს აქ რატომ გაჩნდა? რომელი კომანდ აგამოიყენე კომპონენტის შესაქმნელად?

2023-07-01 22:31 UTC, aberikashvili requested changes
Rebase გააკეთე

2023-07-02 07:29 UTC, developercommon commented on tsconfig.json
generate-ი

2023-07-02 08:11 UTC, developercommon commented on libs/core/src/lib/price/Price.tsx
> +      <Text style={styles.secondaryText}>00</Text>
ეხლა გამახსენდა, toFixed-ით რომ გავაკეთო ისე როგორც დიზაინში არ გამოვა, ამიტომაც ასე უნდა დავტოვო

2023-07-03 13:44 UTC, aberikashvili commented on tsconfig.json
@developercommon `generate` ზოგადი ტერმინია, კონკრეტულად რა კომანდა აკრიფე?

2023-07-03 13:44 UTC, aberikashvili commented on libs/core/src/lib/price/Price.tsx
> +      <Text style={styles.secondaryText}>00</Text>
@developercommon რატომ არ გამოვა?

2023-07-03 14:35 UTC, merged